In [1]:
# numpy, pandas, scikit-learn 패키지 설치
!pip install numpy pandas scikit-learn

  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ------ --------------------------------- 1.8/11.0 MB 9.1 MB/s eta 0:00:02
   ------------- -------------------------- 3.7/11.0 MB 9.1 MB/s eta 0:00:01
   ----------------- ---------------------- 4.7/11.0 MB 8.5 MB/s eta 0:00:01
   -------------------- ------------------- 5.5/11.0 MB 7.1 MB/s eta 0:00:01
   ---------------------- ----------------- 6.3/11.0 MB 6.5 MB/s eta 0:00:01
   -------------------------- ------------- 7.3/11.0 MB 6.0 MB/s eta 0:00:01
   ----------------------------- ---------- 8.1/11.0 MB 5.7 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.0 MB 5.6 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 5.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ------ -----------

In [2]:
import sklearn

print(sklearn.__version__)

1.7.1


In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import pandas as pd

In [5]:
# 붓꽃 데이터 세트 로딩
iris = load_iris()

iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [7]:
# 데이터 프레임 생성
data = pd.DataFrame(data=iris['data'], columns=iris['feature_names'])
target = pd.DataFrame(data=iris['target'], columns=['target'])

data

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [8]:
target

,target
0,0
1,0
2,0
3,0
4,0
...,...
145,2
146,2
147,2
148,2


In [9]:
df = pd.concat([data, target], axis=1)

df.to_csv('iris.csv', index=False)

df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [10]:
df = pd.read_csv('iris.csv')

df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [11]:
# 학습 데이터, 테스트 데이터 분류
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=11)

In [12]:
X_train

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
120,6.9,3.2,5.7,2.3
122,7.7,2.8,6.7,2.0
49,5.0,3.3,1.4,0.2
29,4.7,3.2,1.6,0.2
...,...,...,...,...
76,6.8,2.8,4.8,1.4
13,4.3,3.0,1.1,0.1
81,5.5,2.4,3.7,1.0
91,6.1,3.0,4.6,1.4


In [13]:
X_test

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
112,6.8,3.0,5.5,2.1
145,6.7,3.0,5.2,2.3
133,6.3,2.8,5.1,1.5
56,6.3,3.3,4.7,1.6
111,6.4,2.7,5.3,1.9
9,4.9,3.1,1.5,0.1
65,6.7,3.1,4.4,1.4
15,5.7,4.4,1.5,0.4
30,4.8,3.1,1.6,0.2
63,6.1,2.9,4.7,1.4


In [14]:
y_train

,target
0,0
120,2
122,2
49,0
29,0
...,...
76,1
13,0
81,1
91,1


In [15]:
y_test

,target
112,2
145,2
133,2
56,1
111,2
9,0
65,1
15,0
30,0
63,1


In [16]:
# 모델 생성
dt_clf = DecisionTreeClassifier(random_state=11)

In [18]:
# 학습 수행
dt_clf.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,11
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [19]:
# 예측
pred = dt_clf.predict(X_test)

pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [20]:
y_test

,target
112,2
145,2
133,2
56,1
111,2
9,0
65,1
15,0
30,0
63,1


In [22]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [25]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


In [28]:
# 예측하기
new_data = [[5.1, 3.0, 3, 1.2]]
new_pred = dt_clf.predict(new_data)

new_pred

C:\Users\ITSC\PycharmProjects\PythonProject\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [29]:
# 학습 모델 덤프
import joblib
joblib.dump(dt_clf, 'model.joblib')

['model.joblib']

In [30]:
# 학습 모델 로드(불러오기)
load_model = joblib.load('model.joblib')

In [31]:
# 예측하기
load_model.predict(new_data)

C:\Users\ITSC\PycharmProjects\PythonProject\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])